Create .gitkeep
filetrust/k8-slack-bot pull request #17
Opened 2020-09-11 02:01 UTC by jcanales

2020-09-11 09:48 UTC, yardenshoham requested changes
@jcanales Please remove `img/.gitkeep` and rename `img/Workflow_Diagram_k8-slackbot.png` to `res/workflow-diagram-k8s-slackbot` or `resources/workflow-diagram-k8s-slackbot`.

2020-09-11 09:48 UTC, yardenshoham commented on README.md
> +Objective: Create a slackboot that can integrates with our different endpoin tools to enable the enduser to interact with data from the different endpoints. Endpoints and command list will evolve dep
```suggestion
Objective: Create a slack bot that can integrate with our different endpoint tools to enable the end user to interact with data from the different endpoints. Endpoints and command list will evolve depending on the needs of the projects. 
```

2020-09-11 11:00 UTC, yardenshoham commented
You still didn't rename the `png` file.

2020-09-11 11:05 UTC, yardenshoham approved these changes

2020-09-12 18:02 UTC, DinisCruz approved these changes

2020-09-12 18:03 UTC, merged